[project]
name = "esp32-binary-flash"
version = "0.1.0"
description = ""
authors = [
    {name = "Christophe",email = "christophe.lanouette@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "esptool (>=5.1.0,<6.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
